pp_ag/urls.py
from django.urls import path
from . import views
from django.conf.urls import re_path

app_name = 'ag'

urlpatterns = [
    path('', views.index, name="home"),
    re_path('signup/', views.signup, name='signup'),
    path('case/', views.PostCreateView.as_view(), name="case_post"),
    path('list/', views.PostListView.as_view(), name="case_list"),
    path('case/<int:pk>/', views.CaseDetail.as_view(), name="case_detail"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('case/<int:pk>/edit', views.CaseUpdateView.as_view(), name="case_update"),

    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate_account, name='activate'),
    
]

ppa_g/urls.py
from django.contrib import admin
from django.urls import path, include
from pp_ag import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pp_ag.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pp_ag/models.py
from django.db import models
from django.urls import reverse
from .validators import validate_audio_size, validate_video_size


# Create your models here.

class User(models.Model):
    email = models.EmailField(blank=True)
    
    def __str__(self):
        return self.email

class Case(models.Model):
    project_name = models.CharField(max_length=256, blank=False)
    description = models.TextField(blank=False)
    goal = models.TextField(blank=False, null=True)
    cover_image = models.ImageField(null=True, blank=False, upload_to='covers')
    height_field=models.IntegerField(default=0)
    width_field=models.IntegerField(default=0)
    
    image1 = models.ImageField(null=True, blank=True, height_field='height_field', width_field='width_field', upload_to = 'pictures/')

    image2 = models.ImageField(null=True, blank=True, height_field='height_field', width_field='width_field', upload_to = 'pictures/')

    image3 = models.ImageField(null=True, blank=True, height_field='height_field', width_field='width_field', upload_to = 'pictures/')

    image4 = models.ImageField(null=True, blank=True, height_field='height_field', width_field='width_field', upload_to = 'pictures/')
    
    audio = models.FileField(blank=True, upload_to='audio', validators=[validate_audio_size])
    video = models.FileField(blank=True, upload_to='video', validators=[validate_video_size])
    document = models.FileField(blank=True, upload_to='document')

    def __str__(self):
        return self.project_name
    
    def get_absolute_url(self):
        return reverse("ag:case_detail", kwargs={"pk": self.pk})

pp_ag/forms.py
from django import forms
from .models import User, Case
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .grade_ten_student_data import Twenty_Twenty_Grade_Ten_Student_Data
from django.core.exceptions import ValidationError
from django.contrib.auth import models

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class UserSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, required=True,
                            help_text='Required. Please use a valid Ridley College Email.')
    class Meta:
        model = models.User
        fields = ('username','email', 'password1', 'password2')
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Please use Firstname_Lastname as your username'
        self.fields['email'].widget.attrs['placeholder'] = 'Firstname_lastname@Ridleycollege.com'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

        
    def clean_email(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        if email not in Twenty_Twenty_Grade_Ten_Student_Data:
            ValidationError("Please make sure you are a grade 10 student and use valid Ridley College Email.")
        return email


class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields=('__all__')
    
    
        widgets = {
            'project_name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'description': forms.Textarea(
                attrs={'placeholder': 'Enter description here'}),
        }

pp_ag/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView,DetailView,TemplateView, UpdateView
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django .urls import reverse_lazy, reverse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.http import HttpResponseRedirect
from django.contrib.auth import login

# Create your views here.

# home page
def index(request):
    return render(request, 'index.html')

# user signup
def signup(request):
    if request.method=="POST":
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)

            email_subject = "Activate Your Account"
            message = render_to_string('activate_account.html',{
                'user': user,
                'domain': current_site.domain,
                'uid': str(urlsafe_base64_encode(force_bytes(user.pk))),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.content_subtype = "html"
            email.send(fail_silently=False)

            return render(request, 'send_email_confirmation.html')
    else:
        form=UserSignUpForm()
        
    return render(request,'registration.html', {'form': form})


def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = auth.models.User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, auth.models.User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        url = reverse('ag:home')
        return HttpResponseRedirect(url)
    else:
        return render(request, 'invalid_link.html')


# upload project
class PostCreateView(CreateView, LoginRequiredMixin):
    login_url = '/signup/'
    redirect_field_name = 'registration.html'

    model = Case
    form = CaseForm
    fields = ['project_name','description', 'goal', 'cover_image', 'image1', 'image2', 'image3', 'image4', 'audio', 'video','document']
    template_name = "case_form.html"


# project list
class PostListView(ListView):
    model = Case
    select_related=('first_name', 'last_name', 'cover_image')
    template_name='case_list.html'


# Detail information for each project
class CaseDetail(DetailView):
    model = Case
    template_name='case_detail.html'


# about me page
class AboutView(TemplateView):
    template_name = 'about.html'

# 
class CaseUpdateView(UpdateView):
    form_class=CaseForm
    model = Case
    template_name = "case_update.html"

templates/about.html
{% extends 'base.html' %}

{% block body %}
<br>
    <div class="jumbotron">
        <h1 class="display-4" style="font-weight: bold; font-size:40px;">Hello, Aaron’s here,</h1>
        <p class="lead">I’m currently a grade 10 student at Ridley College. 
        The story of this website originated with Covid. Because of the Covid protocol, 
        a Ridley tradition, offline Personal Project showcase, had to be cancelled. 
        Base on my personal interest in programming and website development, 
        I decided to build a virtual showcase website for Ridley, 
        which continues the Ridley tradition. I believe this virtual showcase also helps people, 
        who cannot attend our offline showcase, to join the showcase remotely. 
        Hope you enjoy this only showcase and website!</p>   
    </div>

{% endblock body %}

templates/activate_account.html
<div style="text-align: center;">
    <br>
    <h1>Verify Your Email</h1>
    <br>
    <hr>
    <p>Hi {{ user.username }}, please verify your email to secure your account.</p>
    <br>
    <div style="text-align: center;">
        <a href="{% autoescape off %} http://{{ domain }}{% url 'ag:activate' uidb64=uid token=token %} {% endautoescape %}">
            <button style="background-color: #C96214;  border: none;  color: white;
  padding: 15px;  text-align: center;  text-decoration: none;  display: inline-block;  font-size: 16px;  cursor: pointer;   border-radius: 10px;">
                Verify Now
            </button>
        </a>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %} " type="text/css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"
            type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <link rel="shortcut icon" type="image/png" href="{% static 'image' %}"/>
    <title>Document</title>
</head>
<body>
<div class="background" style="font-family: 'Montserrat';">
    <nav class="navbar navbar-expand-lg navbar-light" id="outsideNav">
        <a class="logo_container" class="navbar-brand" href="/"><img id="logo"src="https://ridleytigertickets.herokuapp.com/static/tickets/img/RidleyCollege_RGB_C.fd3fcb09409d.jpg"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>            
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" id="link" href="{% url 'ag:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="link" href="{% url 'ag:case_list' %}">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="link" href="{% url 'ag:about' %}">About me</a>
                </li>
                {% if user.is_authenticated %}
                    {% if case %}
                        <li class="nav-item">
                            <a class="nav-link" id="link" href="{% url 'ag:case_update' pk=case.pk %}">Update</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" id="link" href="{% url 'ag:case_post'%}">Upload</a>
                        </li>
                    {% endif %}

                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item dropdown user" id="user">
                            <a class="nav-link dropdown-toggle" href="#" role="buttom" id="email" data-toggle="dropdown">{{user.email}}</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a href="{% url 'password_reset' %}" class="dropdown-item">Reset Password</a>
                                <div class="dropdown-divider"></div>
                                <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    </ul>

                {% else %}
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item dropdown" id="user">
                            
                            <a class="nav-link dropdown-toggle" href="#" role="buttom" id ="email" data-toggle="dropdown">
                                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="white" class="bi bi-person-circle" id="user" viewBox="0 0 16 16">
                                    <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                                    <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                    <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                                </svg>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" id ="email">
                                <a href="{% url 'ag:signup' %}" class="dropdown-item">Sign Up</a>
                                <div class="dropdown-divider"></div>
                                <a href="{% url 'login' %}" class="dropdown-item">Login</a>
                            </div>
                        </li>
                    </ul>
                {% endif %}

                
            </ul>
        </nav>
    <div class="container">
        
        {% block body %}
        {% endblock body %}
        {% block content %}
        {% endblock content %}
    </div>
    <footer class="py-3 bg-dark text-white-50" id="footer" style="width: 100%">
        <div class="container text-center">
            <small>&copy; 2021 Qilin Gu</small>
        </div>
    </footer>
</div>

</body>
</html>

templates/case_detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <br>
    <div class="jumbotron">

        <h1>Project: {{case.project_name}}</h1>
        <h4>Made by {{user.username}}</h4>
        <hr>

        <p>Description: {{case.description}}</p>
        <br>
        <p>Goal: {{case.goal}}</p>
        <img src="{{case.cover_image.url}}">
        {% if case.image1 %}
            <img src="{{case.image1.url}}">
        {% endif %}
        {% if case.image2 %}
            <img src="{{case.image2.url}}">
        {% endif %}
        {% if case.image3 %}
            <img src="{{case.image3.url}}">
        {% endif %}
        {% if case.image4 %}
            <img src="{{case.image4.url}}">
        {% endif %}

        {% if case.audio %}
            <audio controls>
            <source src="{{case.audio.url}}">
            Your browser does not support the audio element.
            </audio>
        {% endif %}

        {% if case.video %}
            <video width="320" height="240" controls>
            <source src="{{case.video.url}}">
            </video>
        {% endif %}

        {% if case.document %}
        {% endif %}

        <hr>
        <a class="btn btn-primary btn-lg button" href="{% url 'ag:case_list' %}" role="button">Back</a>
    </div>
</div>



{% endblock body %}

templates/case_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% if user.is_authenticated %}
    <div class="row justify-content-center">
        <div class="col">
            <br>
            <div style="position: static">
                <h1 class="mt-2 text-dark">Upload Your Personal Project</h1>
                <hr class="mt-1 mb-4 ">
            </div>
            <div class="content-background">
                <form method="POST" enctype="multipart/form-data" class = "form">
                    <p class="note">* Note: you can only upload your personal project once, but you can update it later on.</p>
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-primary button">Post</button>
                </form>
            </div>
            <br>
            <hr class="mt-3 mb-4 ">
        </div>
    </div>
    {% endif %}
{% endblock body %}

templates/case_list.html
{% extends 'base.html' %}

{% block body %}
<h1 class="title ">Gallery</h1>
<hr>
    {% for case in object_list %}
        <div class="jumbotron">
            {% if case.cover_image %}
                {% for case in case_list%}
                    <div class="jumbotron" id="case_jumbotron">
                        <a href="{% url 'ag:case_detail' pk=case.pk %}" class="btn btn-outline-dark" id="case_link">{{case.project_name}}</a>
                        <img src="{{case.cover_image.url}}">
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}

{% endblock body %}

templates/case_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    {% if user.is_authenticated %}
    <div class="row justify-content-center">
        <div class="col">
            <br>
            <div style="position: static">
                <h1 class="mt-2 text-dark">Update Your Personal Project</h1>
                <hr class="mt-1 mb-4 ">
            <div class="content-background">
                <form method="POST" enctype="multipart/form-data" class = "form" id="form">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-primary button">Update</button>
                </form>
            </div>
            <br>
            <hr class="mt-3 mb-4 ">
        </div>
    </div>
    {% endif %}
{% endblock body %}

templates/index.html
{% extends 'base.html' %}

{% block body %}
<br>
<br>
<div class="jumbotron" id = "jumbotron">
  <h1>2021 Ridley College Grade 10 Personal Project Virtual Showcase</h1>
  <hr>
  <h1>Welcome to 2020-2021 Personal Project Online Show Case</h1>
  <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn btn-outline-primary btn-lg button" href="{% url 'ag:case_list' %}">Go to the showcase</a>
</div>

{% endblock body %}

templates/invalid_link.html
{% extends 'base.html' %}

{% block title %}Invalid Link{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <br>
            <div style="position: static">
                <hr class="mt-1 mb-4 ">
                <div class="content-background">
                    <p>Activation link is invalid!</p>
                    <br>
                    <div style="text-align: center;">
                        <a href="/tickets/home">
                            <button class="btn btn-secondary">Return to Home Page</button>
                        </a>
                    </div>
                </div>
                <br>
            </div>
            <hr class="mt-3 mb-4 ">
        </div>
    </div>
</div>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div style="position: static">
                <br><br>
                <div class="content-background">
                    <h1 class="mt-2 text-dark title">Sign Up</h1>
                    <hr class="mt-1 mb-4 ">
                    <br>
                    <p class="note">* Note that only Ridley College grade 10 student can create an account.</p>
                    
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div style="text-align: center;">
                            <button type="submit" class="btn btn-success button">Sign up</button>
                        </div>
                    </form>
                </div>
                <br>
            </div>
            <hr class="mt-3 mb-4 ">
        </div>
    </div>
</div>
{% endblock body %}

templates/send_email_confirmation.html
{% extends 'base.html' %}

{% block content %}
<h1>Email Verification<h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <br>
            <div style="position: static">
                <hr class="mt-1 mb-4 ">
                <div class="content-background">
                    <div style="text-align: center;">
                        <p style="text-align: center;">We have sent you an email, please confirm your email address to complete registration.</p>
                        <br>
                    </div>
                    <div style="text-align: center;">
                        <a href="{% url 'ag:home' %}">
                            <button class="btn btn-secondary">Return to Home Page</button>
                        </a>
                    </div>
                </div>
                <br>
            </div>
            <hr class="mt-3 mb-4 ">
        </div>
    </div>
</div>
{% endblock %}